# Generated by Django 3.0.7 on 2021-12-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='amount_to_pay',
            field=models.IntegerField(default=0, verbose_name='Amount to Pay'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('Pending for review', 'Pending for review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Draft', max_length=100, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='Eligible for payment or not'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='review_by_admin',
            field=models.CharField(default='', max_length=10000, verbose_name='Your Review'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
