# Generated by Django 3.0.7 on 2021-12-15 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20211215_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 20, 40, 5, 393657), verbose_name='DateTime Updated'),
        ),
    ]
