# Generated by Django 3.0.7 on 2021-12-15 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20211215_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('Pending for review', 'Pending for review'), ('Revision requested', 'Revision requested'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Draft', max_length=100, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 22, 9, 32, 766617), verbose_name='DateTime Updated'),
        ),
    ]
